<WorkloadArea>:
    orientation: 'vertical'
    padding: 7
    spacing: 7

    Widget:
        size_hint_y: .194

    BoxLayout:
        orientation: 'vertical'

        MDScrollView:

            MDGridLayout:
                id: box
                cols: 1
                adaptive_height: True

    MDBoxLayout:
        size_hint_y: None
        height: 0

        WorkloadAreaLegend:
            schedule_view: root