INSERT INTO faculties (title, head) VALUES ('ФАИС', 'Суторьма Игорь Иванович')
INSERT INTO departments (title, faculty_id, head) VALUES ('Кафедра `Информатика`', 1, 'Трохова Татьяна Анатольевна')
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-223', 20, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-227', 60, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-229', 60, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-305', 20, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-220', 20, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-531', 60, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-530', 60, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-523', 20, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-540', 20, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('СПОРТЗАЛ', 1000, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-529', 20, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-539', 20, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-520', 60, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-542', 60, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-537', 60, 1)
INSERT INTO audiences (number, number_of_seats, department_id) VALUES ('2-21', 60, 1)
INSERT INTO groups (title, number_of_students, faculty_id) VALUES ('ИП-31', 30, 1)
INSERT INTO groups (title, number_of_students, faculty_id) VALUES ('ИС-31', 30, 1)
INSERT INTO groups (title, number_of_students, faculty_id) VALUES ('ПМ-31', 29, 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Трохова Т.А.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Самовендюк Н.В.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Кудин В.П.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Физ. руководители', 'Профессора', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Шибеко В.Н.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Кравченко О.А.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Романькова Т.Л.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Котова Ю.Е.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Виноградов Э.М.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Щуплов В.В.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Ростокина О.М.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Красовская Н.А.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Кухаренко С.Н.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Захаренко Л.А.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Ковалев А.В.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Сахарук А.В.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Хананов В.А.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Карпов В.А.', 'Профессор', 1)
INSERT INTO mentors (fio, scientific_degree, department_id) VALUES ('Крышнев Ю.В.', 'Профессор', 1)
INSERT INTO schedules (year, term) VALUES (2022, 'Весенний')
INSERT INTO subject_types (title) VALUES ('Лабораторная')
INSERT INTO subject_types (title) VALUES ('Лекция')
INSERT INTO subject_types (title) VALUES ('Практическая')
INSERT INTO subjects (title) VALUES ('Математическое моделирование сложных систем')
INSERT INTO subjects (title) VALUES ('Операционные системы и среды')
INSERT INTO subjects (title) VALUES ('Основы защиты информации')
INSERT INTO subjects (title) VALUES ('Алгоритмы и структуры данных')
INSERT INTO subjects (title) VALUES ('Методы трансляции')
INSERT INTO subjects (title) VALUES ('Избранные главы информатики')
INSERT INTO subjects (title) VALUES ('Разработка приложений для Интернет')
INSERT INTO subjects (title) VALUES ('Теория автоматического управления')
INSERT INTO subjects (title) VALUES ('Микропроцессоры в системах управления')
INSERT INTO subjects (title) VALUES ('Информационное обеспечение систем управления')
INSERT INTO subjects (title) VALUES ('Физическая культура')
INSERT INTO subjects (title) VALUES ('Компьютерные технологии проектирования систем автоматического управления')
INSERT INTO subjects (title) VALUES ('Элементы и устройства систем управления')
INSERT INTO subjects (title) VALUES ('Конструирование технических средств')
INSERT INTO subjects (title) VALUES ('Средства  отображения информации')
INSERT INTO subjects (title) VALUES ('Техническая электродинамика')
INSERT INTO subjects (title) VALUES ('Микропроцессорная техника')
INSERT INTO subjects (title) VALUES ('Электронные промышленные устройства')
INSERT INTO subjects (title) VALUES ('Преобразовательная техника')
INSERT INTO subjects (title) VALUES ('Аппаратура цифровой обработки сигналов')
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (2, 1, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (1, 1, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (2, 2, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (3, 2, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (2, 3, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (2, 3, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (2, 4, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (3, 4, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (5, 4, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (4, 5, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (2, 5, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (5, 6, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (2, 6, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (2, 7, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (3, 7, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (5, 7, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (6, 8, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (11, 8, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (15, 8, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (15, 8, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (6, 8, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (7, 9, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (9, 9, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (8, 10, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (14, 10, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (10, 11, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (13, 12, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (14, 12, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (6, 13, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (14, 13, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (8, 13, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (14, 14, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (16, 14, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (12, 14, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (14, 15, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (12, 15, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (14, 16, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (7, 16, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (12, 16, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (7, 17, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (7, 17, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (9, 17, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (13, 18, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (7, 18, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (15, 18, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (7, 19, 1)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (7, 19, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (7, 20, 2)
INSERT INTO subject_audiences (audience_id, subject_id, subject_type_id) VALUES (11, 20, 1)
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 1, 2, 1, 2, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 1, 1, 1, 2, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 2, 1, 2, 2, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 2, 2, 2, 2, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 3, 2, 3, 2, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 3, 1, 3, 2, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 11, 2, 4, 4, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (2, 11, 2, 4, 4, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (3, 11, 2, 4, 4, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 4, 2, 5, 4, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 4, 1, 5, 2, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 5, 2, 6, 2, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 5, 1, 6, 2, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 7, 2, 2, 2, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 7, 1, 2, 3, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 6, 2, 7, 2, 2022, 'Весенний')
INSERT INTO workloads (group_id, subject_id, subject_type_id, mentor_id, hours, year, term) VALUES (1, 6, 1, 7, 2, 2022, 'Весенний')
