<GroupsSchedule>:
    orientation: 'vertical'
    padding: 7
    spacing: 7

    Widget:
        size_hint_y: .194

    BoxLayout:
        orientation: 'vertical'

        MDScrollView:

            MDGridLayout:
                id: groups_cont

                cols: 3
                adaptive_size: True

    MDBoxLayout:
        size_hint_y: None
        height: 0

        GroupsScheduleLegend:
            schedule_view: root
