<MenuHeader>:
    orientation: "vertical"
    adaptive_size: True
    padding: "4dp"

    MDBoxLayout:
        spacing: "12dp"
        adaptive_size: True

        MDIconButton:
            icon: "gesture-tap-button"
            theme_icon_color: "Custom"
            icon_color: 'white'
            pos_hint: {"center_y": .5}

        MDLabel:
            text: "Действия"
            adaptive_size: True
            color: 'white'
            pos_hint: {"center_y": .5}
