<CustomTextInput>:
    text_color: 166/255, 60/255, 82/255, 1
    font_name: "assets/fonts/MontserratAlternates-ExtraBold.otf"
    mode: 'rectangle'
    valign: 'center'
    halign: 'center'
    font_size: 26
    write_tab: False
    hint_text_color_normal: 57/255, 97/255, 133/255, 200/255
    line_color_normal: 57/255, 97/255, 133/255, 200/255
    text_color_normal: 57/255, 97/255, 133/255, 200/255